#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\LoginController::index
    methods:
      - POST

new_trucker:
    path: /truckers
    controller: App\Controller\TruckersController::insert
    methods:
      - POST

get_truckers:
    path: /truckers
    controller: App\Controller\TruckersController::getAll
    methods:
      - GET

get_trucker:
    path: /truckers/{id}
    controller: App\Controller\TruckersController::getOne
    methods:
      - GET

update_trucker:
    path: /truckers/{id}
    controller: App\Controller\TruckersController::update
    methods:
      - PUT

delete_trucker:
    path: /truckers/{id}
    controller: App\Controller\TruckersController::delete
    methods:
      - DELETE

new_truck_type:
    path: /truck_types
    controller: App\Controller\TruckTypesController::insert
    methods:
      - POST

get_truck_types:
    path: /truck_types
    controller: App\Controller\TruckTypesController::getAll
    methods:
      - GET

get_truck_type:
    path: /truck_types/{id}
    controller: App\Controller\TruckTypesController::getOne
    methods:
      - GET

update_truck_type:
    path: /truck_types/{id}
    controller: App\Controller\TruckTypesController::update
    methods:
      - PUT

delete_truck_type:
    path: /truck_types/{id}
    controller: App\Controller\TruckTypesController::delete
    methods:
      - DELETE

new_tracking:
    path: /tracking
    controller: App\Controller\TrackingController::insert
    methods:
      - POST

get_trackings:
    path: /tracking
    controller: App\Controller\TrackingController::getAll
    methods:
      - GET

get_tracking:
    path: /tracking/{id}
    controller: App\Controller\TrackingController::getOne
    methods:
      - GET

update_tracking:
    path: /tracking/{id}
    controller: App\Controller\TrackingController::update
    methods:
      - PUT

delete_tracking:
    path: /tracking/{id}
    controller: App\Controller\TrackingController::delete
    methods:
      - DELETE
